# Generated by Django 2.0.7 on 2018-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spider',
            options={'ordering': ['id'], 'verbose_name': '爬虫'},
        ),
        migrations.RemoveField(
            model_name='spider',
            name='name',
        ),
        migrations.AddField(
            model_name='spider',
            name='reasults',
            field=models.TextField(default=' ', verbose_name='结果'),
        ),
    ]
