# Generated by Django 2.0.7 on 2018-07-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0003_spider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='http://news.baidu.com/', max_length=65536, verbose_name='网址')),
                ('reasults', models.TextField(default=' ', verbose_name='结果')),
            ],
            options={
                'verbose_name': '结果',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='spider',
            options={'verbose_name': '爬虫'},
        ),
        migrations.RemoveField(
            model_name='spider',
            name='reasults',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='url',
        ),
        migrations.AlterField(
            model_name='spider',
            name='name',
            field=models.CharField(default='爬虫', max_length=255, verbose_name='爬虫'),
        ),
        migrations.AddField(
            model_name='result',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='spiders.Spider'),
        ),
    ]
